version: '3'
services:
    backend:
        image: registry.gitlab.propulsion-home.ch/fclerc-fullstack-bootcamp-16/week-7/day-3/motion-deployment:master
        restart: always
        env_file:
          - ./env/prod.env
        volumes:
          - static-files:/static-files
          - media-files:/media-files
          - frontend:/frontend/build
        command: "sh /scripts/run.sh"
        environment:
          SECRET_KEY: ${SECRET_KEY}
        depends_on:
          - postgres

    postgres:
        image: postgres:latest
        env_file:
          - ./env/prod.env
        volumes:
          - postgres_volume:/var/lib/postgresql/data

    nginx:
        image: nginx:latest
        restart: always
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./nginx:/etc/nginx/conf.d
          - static-files:/static-files
          - media-files:/media-files
          - frontend:/frontend
          - /etc/letsencrypt:/etc/letsencrypt

volumes:
  postgres_volume:
  static-files:
  media-files:
  frontend: