name: django_motion
dependencies:
  - python==3.9
  - psycopg2=2.8
  - pip:
      - django==3.2
      - djangorestframework==3.12
      - djangorestframework_simplejwt==4.7
      - gunicorn
      - flake8
      - drf-yasg
